[package]
name = "progetto"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.22.0"
native-dialog = "0.6.4"
screenshots = "0.7.2"
