[package]
name = "screenshot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.26"
eframe = "0.22.0"
image = "0.24.7"
native-dialog = "0.6.4"
screenshots = "0.7.2"
arboard = "3.2.0"


